### ISSUE TITLE
GUI in linux

### ISSUE THREAD

**Issue by gkajitani** [mhalushka/miRge3.0#104]
Dear mhalushka,

I'm trying to install the GUI in ubuntu (22.04), using a conda virtual environment for python3.8 . I'm following the steps in the Linux OS guide (https://mirge3.readthedocs.io/en/latest/installation.html#obtaining-and-installing-gui-application), however, I can only get the miRge3.0 working in CLI. Can you please direct me to a solution for this?

Best,

Gustavo

**Comment by arunhpatil** [comment]
Hi @gkajitani, 

Could you download the [GUI app ](https://mirge3.readthedocs.io/en/latest/installation.html#obtaining-and-installing-gui-application), there you will an icon [GUI](https://mirge3.readthedocs.io/en/latest/quick_start.html#mirge3-0-gui), you can follow the instructions on how to use the GUI after completing the requirements [here](https://mirge3.readthedocs.io/en/latest/quick_start.html#mirge3-0-gui).

Let me know how it goes. 

Thank you,
Arun.

**Comment by gkajitani** [comment]
Hi Arun,

Thanks a lot! I was following the steps with your guide and using the sourceforge link, but I had a small incompatibility that I solved. It now works perfectly.

Thanks,

Gustavo
