### ISSUE TITLE
Issue with Trimmed Reads in Canine miRNA Analysis using miRge3.0

### ISSUE THREAD

**Issue by TomokiMotegi** [mhalushka/miRge3.0#105]
Hello,

Thank you for developing miRge!
I am trying to analyze canine miRNA using miRge3.0. I was able to successfully create custom canine references using miRge-build and ran our data through the pipeline. However, the results seem to show fewer trimmed reads than expected.

Our library was prepared using the QIAseq miRNA library kit, and we used the standard adapter sequence (AGATCGGAAGAGCACACGTCT).

If there are any mistakes in my code or setup, I would appreciate it if you could kindly point them out.

My result
![image](https://github.com/user-attachments/assets/b08ae87a-851f-475d-9213-90ef5474152d)

Code
```
miRge3.0 \
 -s ./Fastq/47-HSA-1_6816_Dog19-28_mix_S6_L001_R1_001.fastq.gz \
 -db miRGeneDB \
 -lib ./miRge3/test/ \
 -on cfa3 \
 -a AACTGTAGGCACCATCAAT \
 --qiagenumi -umi 0,12 -o test_dir -cpu 10 -udd
```

Thank you for your support!

Best regards,
Tomoki

**Comment by arunhpatil** [comment]
Hi @TomokiMotegi, 

I am glad the mirge-build worked out for you. 

Regarding the trimmed reads: I think that this is due to much shorter reads after trimming, we discard all reads that are less than 16 nucleotides in length by default. Also, you are removing PCR duplicates that could also reduce the number of trimmed reads overall. The Unique miRNAs however looks Ok to me.  

Let me know your thoughts. 

Edited: If you could send a sample file, I can have a look. 

Thank you,
Arun.

**Comment by TomokiMotegi** [comment]
Hi Arun,

Thank you so much for your help!
I reviewed the "annotation report" on SourceForge, which shows that the data retains around 74%, making me suspect there may be an issue with my analysis.

I’ve shared my data and the original library at the link below:
[Google Drive Link](https://drive.google.com/drive/folders/1HceZ28h8ZppJBFU1_57DSmMh02Q6Czl9?usp=drive_link)
I apologize for any inconvenience, but I would really appreciate it if you could take a look.

Best regards,
Tomoki

**Comment by arunhpatil** [comment]
Hi @TomokiMotegi,

I had a look at your data, verified for UMI's/adapter and ran with your library (after making changes to the MirGeneDB name) and overall it looks fine. There seems no problem with your analysis or your library. 

Thank you,
Arun.

**Comment by TomokiMotegi** [comment]
Hi Arun,
Thank you for your great support!
I can confidently promote my research.

Best,
Tomoki

**Comment by arunhpatil** [comment]
Hi @TomokiMotegi,

One last thing: If you look at the human miRge library in the annotation.Lib folder, you will find a file called *.merges.*.csv. This file basically denotes miRNA family. In your data, any miRNA which has similar sequences should be clubed before reporting in the miR.Counts.csv or miR.RPM.csv and in your annotation report. 

For example: you obtained 225 miRNAs. However, it can be less than 225 when you club all the similar miRNA sequences. 

grep -B 1 "TGAGGTAGTAGGTTGTATAGTT" Cfa_mature.fasta 
>Cfa-Let-7-P2a1_5p chr1 segs:1-22 cds:-:97904363-97904392
GA`TGAGGTAGTAGGTTGTATAGTT`TTAGGG
--
>Cfa-Let-7-P2a2_5p chr10 segs:1-22 cds:-:20034364-20034393
GG`TGAGGTAGTAGGTTGTATAGTT`TGGGGC
--
>Cfa-Let-7-P1d_5p chr5 segs:1-22 cds:+:12052800-12052829
GT`TGAGGTAGTAGGTTGTATAGTT`TAGAAT

All the above have similar canonical sequence but differ by their name slightly and you may obtain different counts for each of the names (bowtie can't distinguish). Thus, it is ideal to have a name like (miR family), Cfa-Let-7-P2a1_5p/P2a2_5p/P1d_5p denoting all three miRs and sum the counts to this new miRNA name. 

You can fetch all sequences between 2 - 18 nucleotides (canonical sequence) and see if they can be grouped to gather as a family.
Your output in merges file shold be comma seperated as shown below: 
 Cfa-Let-7-P2a1_5p/P2a2_5p/P1d_5p,Cfa-Let-7-P2a1_5p,Cfa-Let-7-P2a2_5p,Cfa-Let-7-P1d_5p

First element in the above line is family name and the rest are looked up in your data by miRge3.0 to sum up the counts and report as Cfa-Let-7-P2a1_5p/P2a2_5p/P1d_5p with xy counts. 

This step is totally optional but ideal. I know it is a lot, let me know if you have any questions. 

Thank you,
Arun.
