### ISSUE TITLE
Installing miRge3.0 on Windows - Error: "Failed building wheel for isal"

### ISSUE THREAD

**Issue by marta-nazzari** [mhalushka/miRge3.0#12]
Hi,
I am trying to install miRge3.0 on Windows 10 following the instructions provided in the documentation.

I am at the step **Installing miRge3.0 with PyPi** > **First install miRge dependencies**. After executing the command `python3.8 -m pip install --user cutadapt reportlab==3.5.42 biopython==1.78  scikit-learn==0.23.1  hypothesis==5.15.1 pytest==5.4.2  scipy==1.4.1  matplotlib==3.2.1  joblib==0.15.1  pandas==1.0.3 future==0.18.2`, at a certain point I get the error `Failed building wheel for isal`. After executing some other lines, the script exists with the message:
> `Command "/usr/bin/python3.8 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e2j491ir/isal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fzsl_opz-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-e2j491ir/isal/`

I cannot find a solution for how to fix this problem. Could you please help me out?

Thank you!

Marta

**Comment by marta-nazzari** [comment]
I found that executing Ubuntu as administrator solved my issue. I'm leaving the original comment in case it can be useful for other people having my same problem.

**Comment by arunhpatil** [comment]
@marta-nazzari, Great (I was looking for a solution and got your reply).
