### ISSUE TITLE
Problem with bam file output

### ISSUE THREAD

**Issue by smackenz1** [mhalushka/miRge3.0#16]
Hi: I'm finding your software very useful but have hit a problem with outputting bam files. The command appears to run without error (Mac OS X 11.4 from terminal) and successfully identifies numerous mature miRNAs:

> $ miRge3.0 -s 01_HAC15_CTRL_01_tr.fastq.gz -lib /Users/smackenz/Documents/bioinfo_working/virtualenvprojects/bioinfo/miRge_data/miRge3_Lib -pbwt /Users/smackenz/Documents/bioinfo_working/virtualenvprojects/bioinfo/bowtie-1.3.0-macos-x86_64 -on human -db mirbase -o output_dir -gff -tcf -bam       
> bowtie version: 1.3.0
> cutadapt version: 2.6
> Samtools version: 1.13
> Collecting and validating input files...
> 
> miRge3.0 will process 1 out of 1 input file(s).
> 
> Cutadapt finished for file 01_HAC15_CTRL_01_tr in 47.3898 second(s)
> Collapsing finished for file 01_HAC15_CTRL_01_tr in 1.596 second(s)
> 
> Matrix creation finished in 0.395 second(s)
> 
> Data pre-processing completed in 50.5281 second(s)
> 
> Alignment in progress ...
> Alignment completed in 32.9438 second(s)
> 
> Summarizing and tabulating results...
> Summary completed in 44.6009 second(s)
> 
> 
> The analysis completed in 128.6987 second(s)
> 

However, the resulting bam, sorted.bam and sorted. bai files are each only 9KB in size and consist of nonsense, eg.:

> ãˇBC‹"d[Õé^9ñ·a"ˇî]vVCöÅNÇ¢H∞$V ^<"«˜Vï}œ◊ÀÆ∂ØÀıwÍî˚„o>ˇÍø˚·á˛ÌªÔ_>‰˜È›∑?~¯Ô?ˇ˝Ø_˛Û˜ø˝˙«o_ﬂ}˚Ú·Øˇ¯%ø˚ÙÂCë1[óRAπ%œ⁄ <u	Úe∂÷NÅ‹ÇT≤@r⁄%π’Q+˙%–4Rõz
Ù¥YÇz∆%êñÎËµÇy	Í®S4Î©`∫%Uß>5Ã˘ñ¥4zJä≠)⁄j:ñoÌ≥‘.µåSr´ü4I’¸ê‹˙ß<gŒ„±€u3Uú[ŒÀ◊åZöä‰Sp]¿HUÒı«äÎ⁄ËY{>/¶\˙w¡OÓÁ≈îK}ÈöÊÁóK{‹J“OE˛t[•'IóCÁkÅñ¢íœﬂæÙ÷CÈü>•ı3ﬁﬂÓï¶&ñMóeñÂ)ÔoõÕ,ùeÕd£åŸ≤í⁄ΩgÿL≤qØõ•èÁñ%W€°QYÊG©zX€d›>ßΩ'ñ
ﬂN§$õ&”â¯z Jäu#íeìµV'ÌY$ˆÏ≥íÃÆ¨‰úïe›˜L[Ö∑Øäxl~LÏ(…eü?!(™⁄2ôvèu_˙àì!Ï=ÔuÕè2Ày ƒØ¨¥&ìdÍÍıÆºŒŒ“Wù>WÏsMtg§[Ωn2,¬å‘≥c∂ﬁwº}Mue”Æ+˛í4∑kÇ-Is±œ
I{ôù“l>&≤ÛSáú•’Ë?¸åúô´È]“äl⁄“Ô´„,tó√#H•6“{∏rπ&:Âª£ê¸N˙¿9I‰~â˚t~?#¢<—õ˚WCj§+Ò€xq°n™uHàﬁ˛Ç‡ü≈Ì6™&â_‰‘]Ã‹v»Zí∂ΩÓ;¸pß"‰I’ÁûŸ„*!∑≤/t;ãE«<(π‡ï|Lìıôf-OY≤œ’ö“ˆì∑/à]q@ÔπKÊ-Û8Æè ¸ˆu^5…Æ•¬cÖ÷Õ¯≤Êæñ¶≠à_ÇÆT∫€≥ÀëÖMdŸ

I can see large sam files (several MB) for miRNA, snoRNA, etc. being generated while the command runs, but these disappear at the end.

The collapsed fasta, gff, miR.Counts and miR.Counts files are generated without problem.

Could you suggest what the problem might be?

Many thanks.

**Comment by arunhpatil** [comment]
Hi @smackenz1, 

These files are binary and can be viewed by the command `samtools view input_file.bam | less`, however, the file size of 9kb is very low. Can you download and use this [library ](https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/mhalush1_jh_edu/EdGdF_Wu4KlJs4z3oZinqp0BMhma1QSQgJOUadCb1lSQag?e=MIBIN7) and rerun miRge3.0? Also, you can visualize the `sorted.bam` in [IGV](https://software.broadinstitute.org/software/igv/).  
Please let me know if you have any further questions. 

Thanks, 
Arun

**Comment by smackenz1** [comment]
Hi Arun,

Thanks for getting back to me so quickly. 

The small bam files were empty: nothing in them at all when examined with samtools. However, by using the new library you provided, I was able to generate much larger bam files (56MB from a 266MB input) which, when opened in IGV showed clear alignment of the abundant miRNAs. Other results appear identical to those produced with the previous library.

I assume I should use this new library for all future analyses. Could you outline the differences between this library and the previous one, which is the one recommended in the mirage3.0 documentation at https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/mhalush1_jh_edu/EYMFZao-I4pGrvXbooaW25UBfNaVyO60tn3B0NUPh1dDMA?e=he2DHq

Many thanks again,

Scott

**Comment by arunhpatil** [comment]
Hi @smackenz1, 

Great. This library is identical to the one provided in the documentation, except for one major difference explained below. 

`This library contains the genomic coordinates on the header sequences of the indexed Fasta files. This was handled in a slightly different way in the previous library and scripts.  Further, the sequences were updated for miRGeneDB reference annotations (miRBase annotations remain the same).   We are testing this change of miRGeneDB with various parameters and this library will be made public soon. I hope this answers your queries. `

Thank you, 
Arun

**Comment by smackenz1** [comment]
Hi Arun,

Apologies for the delayed reply to your informative post. That is very helpful and I appreciative your speedy response.

Many thanks,

Scott

**Comment by francois-a** [comment]
Hi, I ran into this issue as well (empty BAMs) and tried the library you posted above, which fixed it. Are the exact reference files/versions that were used to generate this documented/available somewhere?

**Comment by arunhpatil** [comment]
@francois-a, 

Hi, if you are using IGV, you should see an option of changing strand direction for the reference (In the reference track) and yes, it was intentional (to complement the sequences) to match the reverse strand. If you think something is not adding up then can you post a screenshot of IGV here?  

Thank you,
Arun

**Comment by arunhpatil** [comment]
@francois-a ,

We have now corrected the strand FLAGS information in the BAM files. Thank you for bringing this issue. 

Arun
