### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sagarutturkar** [mhalushka/miRge3.0#17]
Hello,

Thank you for providing such a comprehensive tool and it generates a very nice report. I have couple of questions:

1. Is there any way we could run this tool in strand-specific manner? I have seen options (#0: nonstranded;  1: forward strandness;  2: reverse strandness) in other tools.  
2. Can you please confirm the genome versions for human/mouse/rat. Based on date shown on source Forge page, I assumed these are latest genomes (hg38, mm10 and rn6).

 

Thanks
Sagar

**Comment by mhalushka** [comment]
Sagar,
   Thank you for the note.
1. Unfortunately we do not have miRge3.0 designed to run in a strand-specific manner. I don't know how to set that up.
2. Yes, it is hg38, mm10 and rn6.

Cheers,
Marc

**Comment by sagarutturkar** [comment]
Thank you for the quick response. I have seen strand-specific options available in [Quickmirseq](https://baohongz.github.io/guide/QuickMIRSeq.html). 

This option is available in most tools that perform read-counting from BAM. I am not sure what is implemented in miRge3.0, but Htseq, feature-counts, RSEM are most common counting tools and they have these option already implemented. If one of these tools is used, it might be simple to pass this option to counting tool. Hope this helps.

Nonetheless, the miRge3.0 is a very comprehensive and very useful in our analysis. Thanks.
