### ISSUE TITLE
adaptor trimming

### ISSUE THREAD

**Issue by Cristinex** [mhalushka/miRge3.0#20]
Hi, all,

It is confusing to have "illumina" for parameter -a, which specify an adaptor sequence. Does any one know what it means and what are other potential choices?

Thank you.

**Comment by Cristinex** [comment]
Thank you very much for your fast reply!!

I tried to modify the -a parameter. However, the visualization still not working.

For the -dex, I did not receive any error message. I wonder how miRge know how to group the samples into comparison when there are several replicates? Are multiple condition allowed?

I tried to use SRR4005437.fastq.gz and other 5 samples in the same GEO for illumina trimming. It also returned error:

 File "/path/.conda/envs/miRge/lib/python3.8/site-packages/mirge/libs/summary.py", line 744, in summarize
    subpdMapped['miRNA_cbind'] = subpdMapped[['exact miRNA', 'isomiR miRNA']].apply(lambda x: ''.join(x), axis = 1)
  File "/path/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply
    return op.get_result()
  File "/path/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_empty_result()
  File "/path/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 220, in apply_empty_result
    return self.obj._constructor_sliced(r, index=self.agg_axis)
  File "/path/.local/lib/python3.8/site-packages/pandas/core/series.py", line 305, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/path/.local/lib/python3.8/site-packages/pandas/core/construction.py", line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/path/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1452, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

Thank you again for developing miRge3.0, which is one of the best pipeline for me after it was compared with other more than 40 pipelines. It would be nice if the problems above can be solve quickly.

**Comment by Cristinex** [comment]
Also, where is the data table of the outputs? For example, the statistical data of the length of reads?

I appreciate your reply!

**Comment by arunhpatil** [comment]
> Thank you very much for your fast reply!!
> 
> I tried to modify the -a parameter. However, the visualization still not working.
> 
> For the -dex, I did not receive any error message. I wonder how miRge know how to group the samples into comparison when there are several replicates? Are multiple conditions allowed?
> 
> I tried to use SRR4005437.fastq.gz and other 5 samples in the same GEO for illumina trimming. It also returned error:
> 
> File "/path/.conda/envs/miRge/lib/python3.8/site-packages/mirge/libs/summary.py", line 744, in summarize subpdMapped['miRNA_cbind'] = subpdMapped[['exact miRNA', 'isomiR miRNA']].apply(lambda x: ''.join(x), axis = 1) File "/path/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6878, in apply return op.get_result() File "/path/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result return self.apply_empty_result() File "/path/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 220, in apply_empty_result return self.obj._constructor_sliced(r, index=self.agg_axis) File "/path/.local/lib/python3.8/site-packages/pandas/core/series.py", line 305, in **init** data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True) File "/path/.local/lib/python3.8/site-packages/pandas/core/construction.py", line 465, in sanitize_array subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype) File "/path/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py", line 1452, in construct_1d_arraylike_from_scalar subarr = np.empty(length, dtype=dtype) TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
> 
> Thank you again for developing miRge3.0, which is one of the best pipeline for me after it was compared with other more than 40 pipelines. It would be nice if the problems above can be solve quickly.

Hi @Cristinex,

I suspect there is a conflict with pandas and numpy in your local machine, I want you to upgrade pandas and try the command again. You can upgrade it as shown below (python3.7 if you are using py37):

```
python3.8 -m pip install --user --upgrade pandas
python3.8 -m pip install --user --upgrade numpy
```
or
```
pip3 install pandas --upgrade
pip3 install numpy --upgrade
```

Once this is fixed, you will find all the reports in annotation.report.csv, annotation.report.csv and interactive visualization in miRge3_visualization.html and run log files in the destination folder. 

#

**_Regarding DEX (Differential expression):_**

You need to provide a metadata information along with -dex option `-dex -mdt DESmetadata.csv`, where information in the `-mdt`  will be used in DESeq2 and differential expression will be provided between two groups in R. I am attaching a sample metadata information and command line used for reference. 

`miRge3.0 -s SRR8497647.fastq,SRR8497648.fastq,SRR8497649.fastq,SRR8497650.fastq,SRR8497651.fastq,SRR8497652.fastq,SRR8497653.fastq,SRR8497654.fastq -lib miRge3_Lib -on human -db miRGeneDB -o differential_Exp -a TGGAATTCTCGG -cpu 12 -dex -mdt DESmetadata.csv`

**DESmetadata.csv**
id,group
SRR8497647,Control
SRR8497648,Control
SRR8497649,Control
SRR8497650,Control
SRR8497651,treated
SRR8497652,treated
SRR8497653,treated
SRR8497654,treated
[DESmetadata.csv](https://github.com/mhalushka/miRge3.0/files/7339409/DESmetadata.csv)

Please let me know if you need additional information. 

Thank you,
Arun

**Comment by arunhpatil** [comment]
Hi @Cristinex,

Yes, if your data has no adapter sequences, then you may simply skip the option of `-a` or `-g`. The process of adapter trimming is skipped, however, the FASTQ files do undergo QC measures to avoid poor quality reads. 

Thanks,
Arun.
