### ISSUE TITLE
Installation conflict

### ISSUE THREAD

**Issue by xielab2017** [mhalushka/miRge3.0#24]
I create a new conda environment for miRge3.0, succeefully installed Python 3.8 and r-base. When I type conda install -c bioconda mirge3, it tells me following error
(liwei) [xliwei@master software]$ conda install -c bioconda mirge3
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==9.2=0
  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__cuda==9.2=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

How to solve the incompatability problem for this.

Thanks!
Liwei

**Comment by arunhpatil** [comment]
@xielab2017, I suspect that the C compiler libraries are having conflict with python and r-base. Can you create a new environment and install mirge3 alone as shown below:
```
conda create -n mirge38 python=3.8
conda activate mirge38
conda install -c bioconda -y mirge3
```
The first line creates a new environment "mirge38" with python version 3.8. Second-line activates that environment mirge38 (`conda deactivate` to return to base) and the third command installs mirge3. 

If the error still persists then please try removing r-base and then install mirge3. 

Thank you,
Arun

**Comment by xielab2017** [comment]
Following ur instruction, it shows following error

(mirge38) xliwei@xielab:~/miniconda3/envs$ conda install -c bioconda -y mirge3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.23=0
  - feature:|@/linux-64::__glibc==2.23=0

Your installed version is: 2.23

**Comment by arunhpatil** [comment]
@xielab2017,

Is this a complete error message? If so, this is incompatibility with `glibc`, but I am unable to figure out between what packages/with conda or python. 

1. Can you try the same with python3.7 as follows:
```
conda create -n mirge37 python=3.7
conda activate mirge37
conda install -c bioconda -y mirge3
```
2. Can you tell the conda version and if it is an older version, can you update it? 
```
conda --version
conda 4.9.2 (This is our local system)
```

Thanks,
Arun.

**Comment by xielab2017** [comment]
conda 4.10.3 Here is our conda version. 
I tried Python37 and it works to have mirge3 installed. Do I need to instal r-base?
I go to my sample folder with two miRNA sequence samples (mouse sample) for a trial run. 

Here is my script:
#!/bin/bash
source activate mirge3

miRge3.0  -s LZYR0001.fastq.gz, LZYR0002.fastq.gz -lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse \
-pbwt /home/xliwei/miniconda3/bin/   \
-on mouse -db miRBase -o miRge_temp_output \
-gff -cpu 30

conda deactivate

And then it gives the following erroor. I assume it is because of python version, am I right?
bowtie version: 1.2.2
cutadapt version: 2.6
Samtools version: 1.7
Collecting and validating input files...

WARNING: File  is neither fastq or fastq.gz format!
Omitting file

WARNING: File  is neither fastq or fastq.gz format!


miRge3.0 will process 1 out of 2 input file(s).

Cutadapt finished for file LZYR0001 in 226.5371 second(s)
Collapsing finished for file LZYR0001 in 0.9539 second(s)

Matrix creation finished in 1.2849 second(s)

Data pre-processing completed in 230.6784 second(s)

Alignment in progress ...
Traceback (most recent call last):
  File "/home/xliwei/miniconda3/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/__main__.py", line 105, in main
    pdDataFrame = bwtAlign(args,pdDataFrame,workDir,ref_db)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/libs/manifoldAlign.py", line 100, in bwtAlign
    alignPlusParse(bwtExec, bwt_iter, pdDataFrame, args, workDir)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/libs/manifoldAlign.py", line 19, in alignPlusParse
    bowtie = subprocess.run(str(bwtExec), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/xliwei/miniconda3/bin/bowtie /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 30 miRge_temp_output/miRge.2021-12-06_09-17-54/bwtInput.fasta' returned non-zero exit status 1.

Another question is, if I have 20 fastq file, My I write a looping circle linux script to read each sample one by one.

**Comment by arunhpatil** [comment]
@xielab2017,

Great, now we have miRge3.0 installed. I don't see any conflicts that may be due to py3.7. 
1. The samples should not be space-delimited `-s LZYR0001.fastq.gz, LZYR0002.fastq.gz` instead it should be `-s LZYR0001.fastq.gz,LZYR0002.fastq.gz`. 
2. I guess the path to library files may be incorrect, can you do the following:
a. Execute `ls /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse` - list the directory 
b. Execute `/home/xliwei/miniconda3/bin/bowtie /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 30 miRge_temp_output/miRge.2021-12-06_09-17-54/bwtInput.fasta` - This bowtie error will tell if the libraries are accessible 

Regarding bash script, you don't need to write a script for 20 samples, there are two options as shown below:
a) Use directory: `-s dir_inputFiles` (where all your input files are in one directory `dir_inputFiles`, do this only if you are sure that the system has enough RAM and that the files are of small size)
b) If option (a) is not feasible, then you can run miRge3.0 twice with 10 files each
c) if you are planning samples to run individually, then definitely you may consider a for loop to process one sample at a time, however, this is not ideal because the loop is executed even before the queue (mirge run for the previous samples) is completed, this might choke the RAM. 

Thanks, 
Arun.

**Comment by xielab2017** [comment]
Here the output 
(mirge3) xliwei@xielab:/home/sdb1/xie/project/LZY_RNAseq/sample/practise$ /home/xliwei/miniconda3/bin/bowtie /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 30 miRge_temp_output/miRge.2021-12-06_09-17-54/bwtInput.fasta
Could not locate a Bowtie index corresponding to basename "/home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse/mouse/index.Libs/mouse_mirna_miRBase"
Command: /home/xliwei/miniconda3/bin/bowtie-align-s --wrapper basic-0 -n 0 -f --norc -S --threads 30 /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse/mouse/index.Libs/mouse_mirna_miRBase miRge_temp_output/miRge.2021-12-06_09-17-54/bwtInput.fasta

**Comment by arunhpatil** [comment]
@xielab2017,

I believe the organism name mouse is duplicated in the path, it should work if we could do it as follows: 
```
miRge3.0 -s LZYR0001.fastq.gz,LZYR0002.fastq.gz -lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index
-pbwt /home/xliwei/miniconda3/bin/
-on mouse -db miRBase -o miRge_temp_output
-gff -cpu 30
```
Here, I modified the -lib option. Please let me know if this works. 

Thanks, 
Arun.

**Comment by xielab2017** [comment]
miRNA_index/mouse, here mouse is a path not an organism. 

(mirge3) xliwei@xielab:/home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index$ ls
mouse  mouse.tar.gz
(mirge3) xliwei@xielab:/home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index$ cd mouse
(mirge3) xliwei@xielab:/home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse$ ls
annotation.Libs  fasta.Libs  index.Libs
(mirge3) xliwei@xielab:/home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse$

**Comment by arunhpatil** [comment]
@xielab2017,

you are correct. However, miRge3.0 looks and appends the name of the organism from the library directory with the name specified `-on mouse`, so it is sufficient to provide the path to the directory containing the library files for human, mouse etc. So, please provide `-lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index ` instead of `-lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/mouse`. The following command should work, please execute this and let me know:

```
miRge3.0 -s LZYR0001.fastq.gz,LZYR0002.fastq.gz -lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index
-pbwt /home/xliwei/miniconda3/bin/
-on mouse -db miRBase -o miRge_temp_output
-gff -cpu 30
```
Thanks,
Arun.

**Comment by xielab2017** [comment]
(mirge3) xliwei@xielab:/home/sdb1/xie/project/LZY_RNAseq/sample/practise$ sh sample.sh
bowtie version: 1.2.2
cutadapt version: 2.6
Samtools version: 1.7
Collecting and validating input files...

miRge3.0 will process 2 out of 2 input file(s).

Cutadapt finished for file LZYR0001 in 227.5928 second(s)
Collapsing finished for file LZYR0001 in 1.313 second(s)

Cutadapt finished for file LZYR0002 in 230.8325 second(s)
Collapsing finished for file LZYR0002 in 4.352 second(s)

Matrix creation finished in 1.5653 second(s)

Data pre-processing completed in 468.4343 second(s)

Alignment in progress ...
Traceback (most recent call last):
  File "/home/xliwei/miniconda3/envs/mirge3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/__main__.py", line 105, in main
    pdDataFrame = bwtAlign(args,pdDataFrame,workDir,ref_db)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/libs/manifoldAlign.py", line 100, in bwtAlign
    alignPlusParse(bwtExec, bwt_iter, pdDataFrame, args, workDir)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/site-packages/mirge/libs/manifoldAlign.py", line 19, in alignPlusParse
    bowtie = subprocess.run(str(bwtExec), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/xliwei/miniconda3/envs/mirge3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/xliwei/miniconda3/bin/bowtie /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index/index/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 30 miRge_temp_output/miRge.2021-12-06_10-28-25/bwtInput.fasta' returned non-zero exit status 1.

**Comment by arunhpatil** [comment]
@xielab2017,

Looks like you have renamed the library folder from `/mouse_ref/miRNA_index/mouse` to `mouse_ref/miRNA_index/index/`. This won't work, please retain as it is downloaded i.e., `/mouse_ref/miRNA_index/mouse` (please rename the folder to its native). While running your command please only provide lib option as shown below: 
`-lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index`

So the complete command looks like this:
```
miRge3.0 -s LZYR0001.fastq.gz,LZYR0002.fastq.gz -lib /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index
-pbwt /home/xliwei/miniconda3/bin/
-on mouse -db miRBase -o miRge_temp_output
-gff -cpu 30
```
and directory list `ls` should show the following:
$ ls  /home/sdb1/xie/reference/mouse/mouse_ref/miRNA_index
mouse
$

**Comment by xielab2017** [comment]
the problems are solved. Thanks!
