### ISSUE TITLE
Predicting novel miRNAs error

### ISSUE THREAD

**Issue by seulalee1008** [mhalushka/miRge3.0#26]
Hello I was wondering if you could help me with one thing. I am trying to run mirge3 and it gave me the following error when Performing prediction of novel miRNAs.

Below is the command

(mirge37) -bash-4.2$ miRge3.0 -s /srv/scratch/zhanglab/rnaseq/humanrnaseq/merged/originalbeforetrimmed/N.fastq.gz -lib /srv/scratch/zhanglab/rnaseq/humanrnaseq/merged/miRge3_Lib -on human -db miRBase -o output_dir -gff -nmir -trf -ai -cpu 16 -a CTGTCTCTTATACACATCT -pbwt /home/z3460355/miniconda3/envs/mirge37/bin -psam /home/z3460355/miniconda3/envs/mirge37/bin -prf /home/z3460355/miniconda3/envs/mirge37/bin

Predicting novel miRNAs

Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/home/z3460355/miniconda3/envs/mirge37/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/z3460355/miniconda3/envs/mirge37/lib/python3.7/site-packages/mirge/__main__.py", line 151, in main
    predict_nmir(args, workDir, ref_db, base_names, pdUnmapped)
  File "/home/z3460355/miniconda3/envs/mirge37/lib/python3.7/site-packages/mirge/libs/novel_mir.py", line 354, in predict_nmir
    samysort = subprocess.run(str(samyExec), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/home/z3460355/miniconda3/envs/mirge37/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/z3460355/miniconda3/envs/mirge37/bin/samtools  sort --threads 16 -O sam -T sample.sort -o output_dir/miRge.2021-12 -07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome_sorted.sam output_dir/miRge.2021-12-07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome.sam' returned non-zero exit status 127.

Thank you

**Comment by arunhpatil** [comment]
@seulalee1008,

Hi, can you execute the following (3) commands and let us know what is the output:
1. `ls -lh output_dir/miRge.2021-12-07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome.sam`
2. `tail -4 output_dir/miRge.2021-12-07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome.sam`
3. `/home/z3460355/miniconda3/envs/mirge37/bin/samtools sort --threads 16 -O sam -T sample.sort -o output_dir/miRge.2021-12 -07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome_sorted.sam output_dir/miRge.2021-12-07_21-34-40/unmapped_tmp/unmapped_mirna_N_vs_genome.sam`

Description: 1. will tell me the size of the file, 2. will give the last four lines of the file, and 3. executes the samtools sort command and this will tell us if the file is empty or corrupt and/or if it is an issue with samtools!

Also, can you tell the samtools version installed? `samtools --version`

Thanks, 
Arun.

**Comment by seulalee1008** [comment]
Dear Arun,

Thank you so much for the reply. I really appreciate it. I just excluded the parameter as I won't be needing it now.
But I was wondering if this is ok. I am using samtools 1.13 and when I looked at the bin file (/srv/scratch/z3460355/miniconda/envs/mirge37/bin) samtools is there as well but it gave me the samtools error below. I am still getting all the output files.


bowtie version: 1.2.3
cutadapt version: 2.6
Samtools error!: samtools, command not found. Type "samtools --version" and check the version
 Use argument -psam <name of the directory>
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Cutadapt finished for file Negative-rpt1_S1_R2_001 in 312.4962 second(s)
Collapsing finished for file Negative-rpt1_S1_R2_001 in 15.7214 second(s)
Matrix creation finished in 12.4843 second(s)

Data pre-processing completed in 349.2802 second(s)

Alignment in progress ...
Alignment completed in 809.7678 second(s)

Summarizing and tabulating results...
Summary completed in 86.8851 second(s)

The analysis completed in 1264.9169 second(s)

Thank you

Kind regards,

Christine (Seul A) Lee, PhD candidate (UNSW)

School of Biotechnology and Biomolecular Sciences

University of New South Wales, Sydney, NSW 2052, Australia

[cid:f4a1a5be-a86a-4405-8d20-23284489a65f]


________________________________

**Comment by arunhpatil** [comment]
@seulalee1008,

Yes, this is fine. 

The Samtools is called during novel miRNA predictions, so, it is an escape plan if python is not finding samtools binary and is not required during the process, it will proceed with ignoring the error. You probably have seen this statement on the command line: 
```
Samtools error!: samtools, command not found. Type \"samtools --version\" and check the version\n Use argument -psam <name of the directory>"
"NOTE: Will not exit unless you encounter this error otherwise"
```

Thanks,
Arun.

**Comment by seulalee1008** [comment]
Dear Arun,

Thank you so much for the clarification!

Appreciate it

Kind regards,

Seul
