### ISSUE TITLE
Error while trying to do differential expression

### ISSUE THREAD

**Issue by Rajeefa** [mhalushka/miRge3.0#33]
Error in DESeqDataSet(se, design = design, ignoreRank) : 
  all variables in design formula must be columns in colData
Calls: DESeqDataSetFromMatrix -> DESeqDataSet
Execution halted

Iam getting this error while trying to run miRNA differential expression .My metadata has two fields samples(fastqfilename) and condition(control,HG,Treatment)
[hg_APN-1.csv](https://github.com/mhalushka/miRge3.0/files/8169886/hg_APN-1.csv)

**Comment by arunhpatil** [comment]
Hi @Rajeefa,

When miRge3.0 process the files, the column name only retains prefix of the sample name. So, in your metadata remove `.fastq.gz` from samples (id). Let me know if you have any further questoins regarding this. 

[DESmetadata.csv](https://github.com/mhalushka/miRge3.0/files/8170176/DESmetadata.csv)

Thank you,
Arun.

**Comment by Rajeefa** [comment]
Thankyou for the prompt reply.
