### ISSUE TITLE
Strand assignment in bam output files

### ISSUE THREAD

**Issue by rolfsoekilde** [mhalushka/miRge3.0#35]
Thanks for a great tool.

I noticed that all the reads are assigned to the positive strand. I understand that this might be a design decision, but it makes it more difficult to work with the alignment files downstream.

Hope you in the future can make an adjustment to assign the reads to the correct strands.

-Rolf

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde,

Thanks for bringing this to our attention. 

For the purposes of Visualization over IGV, the strand/orientation of reads looks fine (as shown below). However, your point is valid, I will add the necessary flags to these files in our next release/patch.  Can you specify what other key features you would like to see in the SAM format required for the downstream analysis. 

Thank you,
Arun.

Here is an example I checked with a test input file on IGV (let-7f-5p: reads that align to negative strand):

![image](https://user-images.githubusercontent.com/10003811/157467658-6d47fcbe-5c70-435b-a045-02ef42bc7e93.png)

and miR-126 for positive strand. 
![image](https://user-images.githubusercontent.com/10003811/157467244-c758797d-42e2-4721-8113-d16a79277e01.png)

**Comment by rolfsoekilde** [comment]
Thanks for putting it on the release plan. I actually don't have any concrete ideas for flags in the sam output. I will come back to this part when I start to use it more actively.

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde, 

Thank you, we have adjusted the FLAGS accordingly and it is displaying the correct SAM/BAM flags. The new release includes this fix and it will be out soon.  

Arun.
