### ISSUE TITLE
Start analysis from collapsed reads

### ISSUE THREAD

**Issue by rolfsoekilde** [mhalushka/miRge3.0#36]
A few suggestions.

Would it be possible to adapt the software to be able to start from the collapsed reads?
The collapsing of reads takes time and does not seem to influence the downstream analysis.
Then eg. it would be possible to re-run an analysis with different settings faster.

An initial check of the paths to the annotation files could a nice feature as well. I might be the only one to type the path to the annotation wrong and then have to restart the analysis after spending all that time trimming and collapsing reads:)

**Comment by mhalushka** [comment]
Interesting ideas.  Thank you for these thoughts.

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde, 

We have now introduced `save and resume` parameters and also created a check for library path. Thank you for your suggestions. You will see this in the new release soon. Please feel free to check out the source code at [GitHub](https://github.com/mhalushka/miRge3.0/blob/master/mirge/__main__.py).

The documentation of its usage can be found [here](https://mirge3.readthedocs.io/en/latest/quick_start.html#save-and-resume-functions). 

Thank you,
Arun
