### ISSUE TITLE
Novel miRNAs error 

### ISSUE THREAD

**Issue by karlaarz** [mhalushka/miRge3.0#38]
Hello, I installed mirge3 using conda:

```
conda list | grep "mirge"
mirge3                    0.0.9              pyh5e36f6f_0    bioconda
```
```
miRge3.0 --version
3.0
```

The first part of the analysis goes smoothly:
```
bowtie version: 1.3.0
cutadapt version: 4.0
Samtools version: 1.3.1
RNAfold version: 2.4.14
Collecting and validating input files...

miRge3.0 will process 29 out of 1 input file(s).

...

Matrix creation finished in 19.7173 second(s)

Data pre-processing completed in 5414.808 second(s)

Alignment in progress ...
Alignment completed in 485.209 second(s)

Summarizing and tabulating results...
Summary completed in 187.6939 second(s)
```

But the problem is in the following step, where I get the following error:

```
Predicting novel miRNAs

Performing prediction of novel miRNAs...
Start to predict
Traceback (most recent call last):
  File "/home/tigem/k.ruiz/miniconda3/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/home/tigem/k.ruiz/miniconda3/lib/python3.7/site-packages/mirge/__main__.py", line 151, in main
    predict_nmir(args, workDir, ref_db, base_names, pdUnmapped)
  File "/home/tigem/k.ruiz/miniconda3/lib/python3.7/site-packages/mirge/libs/novel_mir.py", line 442, in predict_nmir
    screen_precusor_candidates(str(Path(outputdir2)), files, str(Path(outputdir2)/(files+"_features.tsv")), strFileOut, str(rnafoldCmdTmp))
  File "/home/tigem/k.ruiz/miniconda3/lib/python3.7/site-packages/mirge/libs/screen_precusor_candidates.py", line 112, in screen_precusor_candidates
    neighborStateLabel = content1.index('neighborState')
ValueError: 'neighborState' is not in list`
```

I reinstalled and updated mirge3 but still get the same error. 
Do you have any ideas?

Thanks!

**Comment by arunhpatil** [comment]
Hi @karlaarz,

The features file is interconnected between many functions and we need to dig a little deeper to find the cause. If possible, can you share the output directory with this miRge run (That way, it gives an idea, what it was failed finding in the feature file and probably why)? Also, can you just re-run 1 or 2 samples and see if the error still persists? If it still does, can you send that sample or subset and I will run it over and try to troubleshoot. 

Thank you,
Arun.

**Comment by karlaarz** [comment]
Hi @arunhpatil, thanks for the quick response. I did the analysis and it seems to be that this error only happens with two samples because when I exclude those samples, the analysis finishes well.

I downloaded the samples from GEO: https://www.ebi.ac.uk/ena/browser/view/PRJNA489010?show=reads
- SRR7779130
- SRR7779131

Do you think that it might be some kind of issue between the samples and mirge3.0? Will it be possible to know?

Thanks!

**Comment by arunhpatil** [comment]
Hi @karlaarz ,

I executed miRge3.0 for the accessions you mentioned. Here is the output in Zip format. I suspect, that the data is truncated (most common cause during fasterq-dump). 
[output_dir.zip](https://github.com/mhalushka/miRge3.0/files/8575642/output_dir.zip)

I hope this helps. 

Thank you,
Arun

**Comment by karlaarz** [comment]
Thank youvery much, it helped!
