### ISSUE TITLE
miRge3_visualization.html empty 

### ISSUE THREAD

**Issue by ErickMUO** [mhalushka/miRge3.0#39]
Hi I am trying to run miRge3.0 pipeline on my data with this command:

miRge3.0 -s file1_fastq.gz,....,file24_fastq.gz -lib /path/to/miRge3_Lib/ -on rat -db miRBase -o /path/to/output/ -gff -ie -dex- mdt path/to/metadata.csv -ai -cpu 12 -a illumina

However, I noticed several deficiencies. 1)Due to the relative "high number" of samples, the process can't finish primarily because of the exhaustion in temp memory. Because of this situation, i tried to run the pipeline in batches of 6 samples and it works, but the miRge3_visualization.html is empty. All the reports seem fine, even the index_data.js contained the whole data that should be shown in the .html. 2) I tried to run the differential expression analysis with the -dex and -mdt commands however the library ggplot2 is not included. I installed it manually (using conda install -c conda-forge r-ggplot2) in my conda environment, nevertheless, it doesn´t solve the problem. 3) The last would be a recommendation, it would be so nice if the user can personalize the bowtie alignment parameters. 

It is noteworthy to say that it's a nice tool, pretty well documented, and easy to use.

Kind Regards.

**Comment by arunhpatil** [comment]
Hi @ErickMUO,

Yes, you are right about high samples exceedign the memory. When you execute the subset of data, can you check if the run.log file shows run summary? Can you share across the html and associated JS file togather for one batch?
2) Differential expression options works once you run miRge with all samples (which exceeded memory), another option of running this would be (using), R script directly, https://github.com/mhalushka/miRge3.0/tree/master/mirge/rScripts
ex: Rscript difxp_DESeq.R miR.Counts.csv DESmetadata.csv (A template metadata is shown [here](https://github.com/mhalushka/miRge3.0/issues/33#issuecomment-1056991704)). 3) Thank you for recommending personalized parameters. We allow strict settings streamlined to identify accurate small RNA annotations and further, too many parameters might be tricky to choose by from users who may be new to this field. However, could you suggest few parameters that might be necessary to tweak? 

I hope this is helpful. 

Thank you,
Arun

**Comment by ErickMUO** [comment]
Hi, Dr. Arun thank you for the quick response, 

Let me re-run a subset of 6 samples (3 Controls, 3 treatments) so I can specify to you the log message of ggplot2 cause I already checked the run.log, and it did not show the warning I'm telling you. I wil upload the results of this run ASAP(run.log,  .js, and .html). 2) I will also try your R scrip for DE analysis, thank you!. 3) I'm not an expert bioinformatician so I read a bit old paper (Ziemann, et, al. (2016). **Evaluation of microRNA alignment techniques** ) that shares some parameters for the aligners, however, the aligners version are a bit old (i.e. bowtie1 v0.12.8) and I don't know these parameters will work on the latest version. For example, the one they propose for bowtie1: –best –strata -k 1 -m 1.

Regards.

**Comment by ErickMUO** [comment]
I complete the run and now the .html correctly displays the 6 samples xD. I don't what I was doing wrong on the first try.
But the error in ggplot2 persists. It is not reported in the log file:
[run.log](https://github.com/mhalushka/miRge3.0/files/8587421/run.log)

However, on the terminal, it shows this message: 
Matrix creation finished in 147.9001 second(s)

Data pre-processing completed in 5240.6368 second(s)

Alignment in progress ...
Alignment completed in 4900.0908 second(s)

Summarizing and tabulating results...
The number of A-to-I editing sites is less than 10 so that no heatmap is drawn.                                                                
Summary completed in 758.149 second(s)

Performing differential expression...

**Error in library(ggplot2) : there is no package called ‘ggplot2’
Execution halted**

The analysis completed in 11170.5197 second(s)

I couldn't upload the .js and the .html files due to file type restrictions. Sorry :(

**Comment by arunhpatil** [comment]
@ErickMUO,

Ok, I am glad the HTML file display is fine now, (It could just be cashe or memory issue), the ggplot error message has been skipped in the log file by mistake.  The ggplot is most commonly and widely used R package for generating figures, and thus I did not hard code it, which will be revised in the next release. To solve the error about ggplot, here are few recommended steps: 
Installing ggplot using terminal by execute the following commands:    
1. R
2. install.packages('ggplot2',dependencies = TRUE) 
# The above command is borrowed from [stackoverflow](https://stackoverflow.com/questions/32690422/installing-ggplot2-in-r-v3-2-2-says-its-installed-but-is-unable-to-be-found) and would take about 10-15 mis to install
3. q() 
#(it is lower case Q, with parenthesis open and close)
Save workspace image? [y/n/c]: y

If you are familiar with R-studio, execute the same command (install.packages('ggplot2',dependencies = TRUE)) and it is one time installation and it should fix the problem. 

If ones ggplot is installed, you should be able to rerun miRge3.0 to find differential expression. 

Thank you,
Arun.
