### ISSUE TITLE
code to train SVM from miRge2.0 paper

### ISSUE THREAD

**Issue by juancarlosfdc** [mhalushka/miRge3.0#40]
I've found miRge very useful--thanks for making it available! 

I was wondering if you could point me to the code used to train the (human) SVM that's loaded from the .pkl file in model_predict() (line 103 of preprocessFeatureFiles.py). I'm closely following the approach explained in the miRge2.0 paper, but I'm not getting quite the same accuracy. 

Happy to email discuss via email as well.

**Comment by arunhpatil** [comment]
Hi @juancarlosfdc,

The script for SVM was originally written in miRge2.0 and was used in miRge3.0 by changing the syntax of python script to support version 3.0. I am attaching the script and supporting files for your reference. Please note, the script runs for >12 hours to create the models (you may have to install all the supporting packages required for this program, which you can find in the header part of the script). I hope this helps. 

Thank you,
Arun
[juancarlosfdc.zip](https://github.com/mhalushka/miRge3.0/files/8628186/juancarlosfdc.zip)

**Comment by juancarlosfdc** [comment]
Hi @arunhpatil, 

Thank you--I was able to run this successfully to train the SVM. I have another request: do you think you could share the code that was used to generate all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features_updated.csv in the zip file? Here's what I tried to do, following your description in the paper: 

1) download the sequences from NCBI SRA listed in Table 1 of the 2018 miRge2.0 paper. 
2) modify miRge as follows: Don't pass pdUnmapped into predict_nmir() on line 151. Instead, subset pdMapped to the rna type of interest and pass that in. This generates clusters and the associated features out of known reads, hence labeled examples for training and testing the SVM.
3) run the modified miRge on the 33 sequences from NCBI SRA. 

This produced about 5,000 clusters total, so I know I'm going wrong somewhere--maybe in the command line arguments to miRge, or maybe in the modification of the code. If you could share the code you used that would be great. 

Thanks, 
Juan Carlos

**Comment by juancarlosfdc** [comment]
Hi @arunhpatil, 

Sorry to be difficult, I just want to clarify--I cannot find the script that produced all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features_updated.csv in either of these zip files. It sounds like  you don't know where that script is. Is that correct, or am I missing it somehow?

**Comment by arunhpatil** [comment]
Hi @juancarlosfdc, 

My bad, there are several sub-folders and the overall size of the zipped file is >10Gb (from OneDrive). I saw feature detction and the file that is being written to (`all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features.csv`, but later I realized that the output is a stderr).  I found the script and supporting files in a folder which is 240 Mb (zipped) including intermediate output files. If you want all the files in this directory then share your email address and I will send it over google drive. However, for the time being, I only have retained the script and some input files which I think is necessary and is attached for your reference. In case if you find some more input files are required and are not part of this attachment, let me know I will share those specific files as well. I hope this helps. 

Also, note that the output file generated by this script has 10 additional columns which are removed in the updated file (You may consider Pandas drop function to drop those columns). However, the number of rows in both of them remain the same. 

```
$ head -1 all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features.csv | awk -F, ' {print NF}'
84 
$ head -1 all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features_updated.csv | awk -F, '{print NF}'
74
```
[juancarlosfdc_PL15.zip](https://github.com/mhalushka/miRge3.0/files/8764061/juancarlosfdc_PL15.zip)


Thank you,
Arun

**Comment by juancarlosfdc** [comment]
Hi Arun, 

Sorry for my late reply, and thanks for sharing this. Unfortunately, the file that writes  `all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features.csv` (Refine_build_dataset.py, line 22) is simply reading in `all_tissues_mapped_dataset_15_refined_miRGeneDB_tmp.csv` on line 128 and rewriting that input. 

`all_tissues_mapped_dataset_15_refined_miRGeneDB_tmp.csv` doesn't appear to be written by any other script in this directory. So, I'm no closer to generating the original data frame, namely `all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features.csv`. If you can find the code that uses miRge to generate clusters from known annotations and write features associated to each cluster, I think that's what I need.

In the meantime, I've been trying to modify miRge on my own to generate the data frame for myself (and reproduce the SVM performance that depends on it), but the code is challenging and I'm so far unable to generate a data frame that agrees with `all_tissues_mapped_dataset_15_refined_miRGeneDB_total_features.csv`. I'm happy to discuss via email, and thanks for your patience here. 

Best, 
Juan Carlos
