### ISSUE TITLE
Spike-In

### ISSUE THREAD

**Issue by hamzaaitabbou96** [mhalushka/miRge3.0#48]
Hi,

I would like to use the spike-In (using the eption  -spk).
Can you explain me more how to use it 
What we need in input to use it?

**Comment by arunhpatil** [comment]
Hi @hamzaaitabbou96, 

Experiments involving Spike-in reads/standard synthetic reads at different concentrations are sequenced as standards. So, your typical input FASTQ reads would contain these spike-in reads along with miRNAs and other small RNA reads which need to be quantified. An example (and much more discussion on spike-in with other user) has been described in detail in the following issue. If you have any further questions, please let us know. 

https://github.com/mhalushka/miRge3.0/issues/27#issue-1074611243

Thank you,
Arun.

**Comment by hamzaaitabbou96** [comment]
Hi,
I have this index spike :
>spike_1
UUGAUUCCCAAUCCAAGCAAG
>spike_2
UACCAACCUUUCAUCGUUCCC
>spike_3
UCCCAAAUGUAGACAAAGCA

I replaced spike-in data already indexed in miRge by the command bowtie-build,
when i saw the contents of it by the command bowtie-inspect, i got this 

>spike_1
GACCCAACCAAGCAAG
>spike_2
ACCAACCCACGCCC
>spike_3
CCCAAAGAGACAAAGCA

my question why there is a change in the sequences ? (U was deleted from the sequence)
