### ISSUE TITLE
Process hanging/killed at collapsing step

### ISSUE THREAD

**Issue by Ben7124** [mhalushka/miRge3.0#49]
Hello,

I have 12 samples which I am attempting to run through miRge3.0. When it reaches the 8th sample, it just hangs after finishing the Cutadapt stage and is killed. Is there any thing I can do to troubleshoot this issue? My machine has 64GB RAM and 8 cores. 
Thank you.

**Comment by arunhpatil** [comment]
Hi @Ben7124, 

It should ideally not hang. Can you share the command line used and the standard output? Do you specify -cpu option? Are you executing this on a server (Usually, servers have some restrictions if you are using slurm modules, with a cap on RAM to use per user)?  

Thanks,
Arun.

**Comment by Ben7124** [comment]
Thank you Arun. I tried it on another machine and it proceeds through the steps.
