### ISSUE TITLE
Log2FC Values Question?

### ISSUE THREAD

**Issue by Samir-A** [mhalushka/miRge3.0#54]
Hey Arun,

I wanted to ask you a quick question about the Log2 Fold Change values that were made from the miRge command you helped me work through a couple weeks back. 

I wanted to ask if I am supposed to get really high Log2FC values? In the screen shot I sent, I isolated the Log2FC values from the miR.DiffExpn.txt file. It shows the highest Log2FC values for each comparison I ran miRge with and the largest values reach over 10,000. Is this normal with miRNA data or is it some kind of mistake? I also included the miR.DiffExpn.txt file for one comparison.

Thanks in advance,
Samir
[miR.DiffExpn.txt](https://github.com/mhalushka/miRge3.0/files/9213374/miR.DiffExpn.txt)
![log2FC](https://user-images.githubusercontent.com/109101677/181614379-d40d7777-8a06-47ab-bc4f-574108ce999e.png)

**Comment by arunhpatil** [comment]
Hi @Samir-A ,
  
No, it is not high fold change values. It is left shifted, with one missing header name. The common mistake with R is that, it skips the name of the first column (here it is miRNA names). the second column is `baseMean`. So, what you are seeing is the baseMeans, followed by log2FoldChange. I have a sample with out correction of header and another with corrected headers. There are seven (7) columns in total. 

# Raw/incorrect header
```
"baseMean"      "log2FoldChange"        "lfcSE" "stat"  "pvalue"        "padj"
"Hsa-Mir-10-P2a_5p"     3203.24815283636        -0.560109059935109      0.026939549828513       -20.7913296064912       5.18540540993767e-96    2.11564540725457e-93
```

# Clean/correct header
```
"miRNA"    "baseMean"      "log2FoldChange"        "lfcSE" "stat"  "pvalue"        "padj"
"Hsa-Mir-10-P2a_5p"     3203.24815283636        -0.560109059935109      0.026939549828513       -20.7913296064912       5.18540540993767e-96    2.11564540725457e-93
```
I will edit this in the R script to retain the right header information in the next release. 

I hope this helps. 

Thank you,
Arun

**Comment by arunhpatil** [comment]
Hi @Samir-A,

I have revised the column names in the differential expression result file.  

Thank you,
Arun.
