### ISSUE TITLE
Bowtie error

### ISSUE THREAD

**Issue by sanatbhadsavle** [mhalushka/miRge3.0#55]
Hi, on running miRge on one sample, I get the following error - 
`bowtie version: 1.2.3
cutadapt version: 3.1
Samtools error!: samtools, command not found. Type "samtools --version" and check the version
 Use argument -psam <name of the directory>
NOTE: Will not exit unless you encounter this error otherwise
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Cutadapt finished for file QD1065-01_S1_L003_R1_001 in 229.2512 second(s)
Collapsing finished for file QD1065-01_S1_L003_R1_001 in 2.7011 second(s)

Matrix creation finished in 3.4465 second(s)

Data pre-processing completed in 247.1582 second(s)`

After this I get traceback calls like so -
`Alignment in progress ...
Traceback (most recent call last):
  File "/sw/eb/sw/miRge3/0.0.9-foss-2020a-Python-3.8.2/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File "/sw/eb/sw/miRge3/0.0.9-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/mirge/__main__.py", line 105, in main
    pdDataFrame = bwtAlign(args,pdDataFrame,workDir,ref_db)
  File "/sw/eb/sw/miRge3/0.0.9-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/mirge/libs/manifoldAlign.py", line 100, in bwtAlign
    alignPlusParse(bwtExec, bwt_iter, pdDataFrame, args, workDir)
  File "/sw/eb/sw/miRge3/0.0.9-foss-2020a-Python-3.8.2/lib/python3.8/site-packages/mirge/libs/manifoldAlign.py", line 19, in alignPlusParse
    bowtie = subprocess.run(str(bwtExec), shell=True, check=True, stdout=subprocess.PIPE, text=True, stderr=subprocess.PIPE, universal_newlines=True)
  File "/sw/eb/sw/Python/3.8.2-GCCcore-9.3.0/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie /scratch/user/sanatbhadsavle/spermRNAseq/mouse/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 48 output_dir/miRge.2022-08-04_15-02-15/bwtInput.fasta' returned non-zero exit status 1.`

What could be the problem? Thanks.

**Comment by arunhpatil** [comment]
Hi @sanatbhadsavle , 

It seems like the library is not accessible, can you check the path? On the other hand, try executing the following command (taken from the error above):

`bowtie /scratch/user/sanatbhadsavle/spermRNAseq/mouse/mouse/index.Libs/mouse_mirna_miRBase -n 0 -f --norc -S --threads 48 output_dir/miRge.2022-08-04_15-02-15/bwtInput.fasta > test_output.sam`

Basically, the following path should exist and if you say `ls`, it should list several files one of which should be `mouse_mirna_miRBase` with ebwt extensions:
`ls /scratch/user/sanatbhadsavle/spermRNAseq/mouse/mouse/index.Libs/`

Let me know if this helps. 

Thanks,
Arun.

**Comment by sanatbhadsavle** [comment]
Hi Arun,
My bowtie is working fine, `bowtie -h` spits the usual help message.
I also ran the command you mentioned and it gave out this - 
`# reads processed: 757333
# reads with at least one reported alignment: 3210 (0.42%)
# reads that failed to align: 754123 (99.58%)
Reported 3210 alignments`

I should mention that I am running miRge with the Qiagen UMI mode, my original input command was - 
`miRge3.0 -s QD1065-01_S1_L003_R1_001.fastq.gz -lib /scratch/user/sanatbhadsavle/spermRNAseq/mouse/ -db miRBase -on mouse -a AACTGTAGGCACCATCAAT --qiagenumi -umi 0,12 -o output_dir -gff -udd`

**Comment by arunhpatil** [comment]
@sanatbhadsavle,

The command looks fine, the path to -lib seems incorrect. 

For example in my laptop: 
`ls /mnt/d/Halushka_lab/Arun/GTF_Repeats_miRge2to3/miRge3_Lib`
I should see the folder named `mouse` and then 

`ls /mnt/d/Halushka_lab/Arun/GTF_Repeats_miRge2to3/miRge3_Lib/mouse`
Should show the following sub-folders: 
`annotation.Libs `,  `fasta.Libs `, `index.Libs`

Similarly, when you list the folder by the following command:
`ls /scratch/user/sanatbhadsavle/spermRNAseq/mouse/`
you should see the folder named  `mouse` and then 

`ls /scratch/user/sanatbhadsavle/spermRNAseq/mouse/mouse/`
Should show the following sub-folders: 
`annotation.Libs `,  `fasta.Libs `, `index.Libs`

Please let me know if the above paths exist. In case if you have doubts, then try to execute the following command: 
`miRge3.0 -s QD1065-01_S1_L003_R1_001.fastq.gz -lib /scratch/user/sanatbhadsavle/spermRNAseq  -db miRBase -on mouse -a AACTGTAGGCACCATCAAT --qiagenumi -umi 0,12 -o output_dir -gff -udd`
Here I have tweaked your absolute path. 

Thanks, 
Arun

**Comment by sanatbhadsavle** [comment]
@arunhpatil 
Hey,
Thanks for the help, that worked. I just has to take out `/mouse/` from my path.

**Comment by arunhpatil** [comment]
@sanatbhadsavle,

Yay. I am glad it worked out for you. 

Thanks,
Arun.
