### ISSUE TITLE
Update doc for a link o a docker file

### ISSUE THREAD

**Issue by bchatelet** [mhalushka/miRge3.0#59]
I had many difficulties to make mirge3 work on WSL2. I finally manage to do it with docker and push an image on DockerHub: 
https://hub.docker.com/r/bchatelet/mirge3
By the way, I saw that there were already images with the name "mirge3" on docker Hub ?
It would be good to include a link to a tested docker image in the documentation, because the install is a bit tricky..

**Comment by arunhpatil** [comment]
@bchatelet , 

We recommend Conda installation however, pip should simply work too. I agree with you. Sorry for inconvenience caused and thank you for the suggestion about the link. I will update it shortly. 

Thank you,
Arun.

**Comment by arunhpatil** [comment]
Hi @bchatelet,

I have added a badge on the main document, also, provide a link to the same in the installation page. 

Thank you for your suggestion.
Arun.
