### ISSUE TITLE
Resume error

### ISSUE THREAD

**Issue by Glfrey** [mhalushka/miRge3.0#60]
Hello,

I get the following error when running the latest version of miRge3.0 installed via pip when I'm trying to resume a job:

`Traceback (most recent call last):
  File "/Users/gillianreynolds/Library/Python/3.7/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/Users/gillianreynolds/Library/Python/3.7/lib/python/site-packages/mirge/__main__.py", line 157, in main
    pdDataFrame = bwtAlign(args,pdDataFrame,workDir,ref_db)
UnboundLocalError: local variable 'pdDataFrame' referenced before assignment`

**Comment by arunhpatil** [comment]
Hi @Glfrey,

Thank you for reaching out regarding the resume function. I have tested with only a few samples and I will be glad to resolve the issue. Can you please share the command you used? 

Thank you,
Arun.

**Comment by Glfrey** [comment]
Hi @arunhpatil,

Thank you for your rapid response! I have realised the error was on my end, I wasn't providing a directory as input and as such the for loop for reading in the data on line 90 of _main_.py wasn't triggered. Completely my oversight but it may benefit others users to make the mirge throw an error if a directory isn't provided as input but the `--r` flag is specified if you have the time or inclination. 

Thank you,

Gill.

**Comment by arunhpatil** [comment]
Hi @Glfrey,

Thank you, this is an excellent suggestion and I will make this adjustment in our next relase. 

Thank you,
Arun
