### ISSUE TITLE
miRNA reference database

### ISSUE THREAD

**Issue by hamzaaitabbou96** [mhalushka/miRge3.0#65]
Hi,
is there a possibility to change the miRNA reference database (miRBase and miRGeneDB) ?

**Comment by arunhpatil** [comment]
Hi @hamzaaitabbou96, 

Do you mean other than miRBase or miRGeneDB?  If this is correct, then the answer is no. The code is forced to look for these names, however, we can trick the code by calling your own database as either miRBase or miRGeneDB while building it. So the extensions of the files will be `human_mirna_miRBase` and similarly for other miRGeneDB. 

I hope this helps, let us know if you need more information regrading this.

Thank you,
Arun.
