### ISSUE TITLE
Add '.fq' and '.fq.gz' to accepted file extensions

### ISSUE THREAD

**Issue by mckellardw** [mhalushka/miRge3.0#66]
I am trying to add miRge3 to one of my pipelines, and hit a snag where it does not accept '.fq.gz' files- `WARNING: File file.fq.gz is neither fastq or fastq.gz format!`. Could you add these extensions to the accepted options?

**Comment by mckellardw** [comment]
One more request- is there a way to remove the extra date/numbers that is appended onto the output directory name? They make it difficult to work with in workflow managers like snakemake where the file names need to be predictable. Thanks!

**Comment by arunhpatil** [comment]
Hi @mckellardw,

Thanks for your inputs. Regarding the output directory name, It (by default) has a suffix of date and time.  This would be ideal to avoid names with space or special characters. However, you could pass this hidden argument `'-onam'  or  '--outDirName'` with the name of the directory and this should solve the problem. Please let me know if you have any further questions. 

I have added the change to include fq.gz extension at [miRge3.0.miRgeEssential ](https://github.com/mhalushka/miRge3.0/blob/master/mirge/libs/miRgeEssential.py#L109), but this won't reflect until I make the new release. However, will already be part in the next release. 

Thank you for your suggestions. 
Arun

**Comment by mckellardw** [comment]
Thanks very much!
