### ISSUE TITLE
Annotation database access

### ISSUE THREAD

**Issue by Glfrey** [mhalushka/miRge3.0#67]
Hello again!

I was hoping to be able to analyse the annotated miRNA sequences that mirge3.0 returned, however I noticed that the names used by mirge3.0 occasionally differ slightly than those used by mirbase (e.g. via amalgamation of miRNA names via the addition of a "/"). As such I was wondering if you could share the annotated database used by mirge3.0? I can't seem to source it anywhere (although may have missed it).

Many thanks as always,

Gill

**Comment by arunhpatil** [comment]
Hi @Glfrey,

The annotations are clubbed for miRNAs that share similar seed sequences, (family miRNAs), you can find this file in the miRge_lib or (libraries folder that is passed with -lib parameter). In this folder you can find the file that stores this information.

`less human/annotation.Libs/human_merges_miRBase.csv`

Let me know if you have any further questions. 

Thank you,
Arun.
