### ISSUE TITLE
How to input paired-end sequencing data？

### ISSUE THREAD

**Issue by wan230114** [mhalushka/miRge3.0#7]
I want to input paired-end sequencing data, what should I do？

**Comment by mhalushka** [comment]
Hi.  miRge3.0 is not designed for paired-end sequencing data.  I am not sure why you would have paired-end sequencing data for small RNAs.  I think you can convert that data into single-end read using the information provided here: https://www.biostars.org/p/366216/. That converted data should run in miRge3.0.

**Comment by wan230114** [comment]
Thanks. There is really no need to use PE.

**Comment by JFsanchezherrero** [comment]
Yes, there is a need to use PE reads. 
We used PE and demonstrated that single end reads produce artifact sequences when identifiying isomiR sequences.
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04128-1

We developed XICRA to join PE reads and reduce this error:
 in artifact https://github.com/HCGB-IGTP/XICRA

I will be implementing miRge3.0 as an option to execute in the tRF and miRNA/isomiR analysis.

**Comment by mhalushka** [comment]
I read the BMC Bioinformatics piece.  It is very nice work. I agree that PE is useful for better understanding isomiRs and distinguishing them from read errors.  However, in general, PE will not be used.  Therefore, we will not be focusing our time on making miRge3.0 able to use PE sequencing.  The community probably needs only one tool and if XICRA works for this purpose, that would be great. But if you want to tweak miRge3.0 to do this, please feel free to do so.

**Comment by JFsanchezherrero** [comment]
Hi there,
Thank you very much for your reply and comments. The idea of XICRA is to create a single error-free read by joining the paired-end reads. So the idea is to use miRge3.0 along other software already called in the pipeline such as miraligner, srnabench etc. 

I have another question but I will open other isue

Regards
