### ISSUE TITLE
installation with mac os

### ISSUE THREAD

**Issue by mick42-star** [mhalushka/miRge3.0#81]
Hi there,

I tried to install miRge 3.0 into my mac. it seems the file has been moved to other place. Would you please give some suggestions?

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl: (22) The requested URL returned error: 404

**Comment by arunhpatil** [comment]
Hi @mick42-star ,

You could download the Homebrew set up and install as described for [the macOS .pkg installer](https://docs.brew.sh/Installation). 

The download link for Mac is provided [here](https://github.com/Homebrew/brew/releases/tag/4.1.4)

Let me know how it works. 

Thank you,
Arun.

**Comment by mick42-star** [comment]
Thanks！It works well.
