### ISSUE TITLE
differentially expressed hairpin miRNA

### ISSUE THREAD

**Issue by mick42-star** [mhalushka/miRge3.0#82]
Hi there, I noticed that although it can identify the amount of hairpin miRNA, mature miRNA and etc. But in the miR.counts.csv, it only contains counts for mature miRNA. I wonder if I want to know the differentially expressed hairpin miRNA, how can I get the counts for that?

Thanks

**Comment by arunhpatil** [comment]
Hi @mick42-star 

If you look at the mapped.csv file, it has read counts for each RNA species types. You could extract this information for hairpin by using a grep search as shown below:

`grep "1,,hsa"  output_dir/miRge.2023-07-24_16-04-40/mapped.csv `

You can then sum total of counts for each miRNA across all samples. 

Thank you,
Arun.
