### ISSUE TITLE
Spike-In

### ISSUE THREAD

**Issue by hamzaaitabbou96** [mhalushka/miRge3.0#84]
Hi,
I have this index spike :

spike_1
UUGAUUCCCAAUCCAAGCAAG
spike_2
UACCAACCUUUCAUCGUUCCC
spike_3
UCCCAAAUGUAGACAAAGCA

I replaced spike-in data already indexed in miRge by the command bowtie-build,
when i saw the contents of it by the command bowtie-inspect, i got this

spike_1
GACCCAACCAAGCAAG
spike_2
ACCAACCCACGCCC
spike_3
CCCAAAGAGACAAAGCA

my question why there is a change in the sequences ? (U was deleted from the sequence)

**Comment by arunhpatil** [comment]
Hi @hamzaaitabbou96,

The bowtie-build ignores the U's from your file. We have to replace the U's to T's in your file before you index it with bowtie. I have under [accessories](https://github.com/arunhpatil/miRge3_build/tree/main/mirge_build/accessories)  uploaded a python script that converts the U's to T's. 

`If you are familiar with Git clone, you can skip the following steps and simply clone it to your computer.` 
Downloading the script on your computer:
Step 1: Go to https://github.com/arunhpatil/miRge3_build/tree/main
Step 2: Click on Code, and select "Download zip", 
Step 3: unzip the folder and change directory to mirge_build/accessories (you will find the script under this folder).

Script usage:
`python  replace_UT.py  test.fasta `
Where test.fasta is your spike in fasta file, and the script generates the output with suffix `_U2T.fasta`. 
bowtie-build: 
`bowtie-build test_U2T.fasta human_spike-in` 

I hope this helps and solve the problem. 

Thank you,
Arun.
