### ISSUE TITLE
installation on mac OS

### ISSUE THREAD

**Issue by rolfsoekilde** [mhalushka/miRge3.0#85]
I have some issues installing the newest version of mirge3 on mac OS.

I have tried to install it with conda in various ways.
eg with:
conda install -c bioconda mirge3

anaconda3/envs/mirge3new/lib/python3.10/site-packages/mirge/libs/digest.py", line 319, in cutadapt
    if int(cu_ver) >= 3:
NameError: name 'cu_ver' is not defined

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde,

This is interesting. I think, this is not the problem of installation, but rather the version of Python, as I have defined cu_ver at line 110 and 111 ([here](https://github.com/mhalushka/miRge3.0/blob/master/mirge/libs/digest.py#L111)). I think the latest version of python is not considering the global declaration of variables. Can you test the same by creating a new environment with python==3.8 or upto 3.10? (any version less than the current python version installed on your OS). 

Let me know how this goes. 

Thank you,
Arun.

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde, 

Sorry for this inconvenience. I will check with this version of cutadapt and their changes. Can you downgrade to cutadapt 4.2 and please let me know if this works? 

Thank you,
Arun.

**Comment by rolfsoekilde** [comment]
Hi Arun,

Thanks for your assistance.
I am afraid I get the same error message with cutadapt 4.2 for python3.8, 3.9 and 3.10.

By the way there is a warning when running the miRge3.0:
pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde,

This is a new bug, I will test with newer version of cutadapt. This might be a simple fix, I will have to get back to you on that. In the meanwhile, can you check with Python 3.7.15 version?

Also, please ignore the warning, this is a reminder for the future updates of using that Bio function which will be updated in miRge as well. 

Thank you,
Arun.

**Comment by rolfsoekilde** [comment]
Hi Arun,

Thanks for your efforts.

Here I get another error with dnaio.

Traceback (most recent call last):
  File "/anaconda3/envs/mirge3715/bin/mirge3.0", line 6, in <module>
    from mirge.__main__ import main
  File "/anaconda3/envs/mirge3715/lib/python3.7/site-packages/mirge/__main__.py", line 17, in <module>
    from mirge.libs.digest import baking 
  File "/anaconda3/envs/mirge3715/lib/python3.7/site-packages/mirge/libs/digest.py", line 2, in <module>
    import dnaio
ModuleNotFoundError: No module named 'dnaio'

**Comment by arunhpatil** [comment]
Hi @rolfsoekilde,

Can you install dnaio with conda, `conda install -c bioconda dnaio==0.3`. I have 0.3 version for py 3.7.15. Hope this will work. Let me know how this goes.  

Thank you,
Arun.

**Comment by rolfsoekilde** [comment]
Hi @arunhpatil

A new error from the python 3.7.15 installation, after dnaio installation.

Traceback (most recent call last):
  File "anaconda3/envs/mirge3715/bin/mirge3.0", line 6, in <module>
    from mirge.__main__ import main
  File "anaconda3/envs/mirge3715/lib/python3.7/site-packages/mirge/__main__.py", line 17, in <module>
    from mirge.libs.digest import baking 
  File "anaconda3/envs/mirge3715/lib/python3.7/site-packages/mirge/libs/digest.py", line 12, in <module>
    from cutadapt.adapters import warn_duplicate_adapters
ImportError: cannot import name 'warn_duplicate_adapters' from 'cutadapt.adapters' (anaconda3/envs/mirge3715/lib/python3.7/site-packages/cutadapt/adapters.py)

thanks,
Rolf

**Comment by arunhpatil** [comment]
Hi Rolf, 

I am trying to reproduce the error on a Mac env. This one is M2 (arch) and has issues with conda installation. However, that was wierd to encounter missing `warn_duplicate_adapters` function. What version of cutadapt are you using? If I am able to install the latest version on Mac, I will be able to resolve the issue and I am sure, other users will encounter this issue in the future with cutadapt version change. I will try reproduce this error in Ubuntu. 

What is the cutadapt version you are using?

Thank you,
Arun.

**Comment by rolfsoekilde** [comment]
Hi Arun,

I have a M1.

For the python 3.7.15 it is cutadapt==1.18.
python 3.8, 3.9, 3.10 cutadapt==4.2.

best,
Rolf

**Comment by arunhpatil** [comment]
Hi Rolf, 

Sorry for this inconvenience. I can't figure out the error, I will work with the latest version of cutadapt and try to fix the bug. With 4.2 version, one should not get the error of `cu_ver` not defined.  Can you print complete error starting from the command mirge3, as it shows the version of cutadapt used. I will debug this in couple of days. 

In the meanwhile, if you could install with pip instead of conda, and let me know if the error still persists?

Thank you,
Arun.

**Comment by rolfsoekilde** [comment]
Hi Arun,

Thanks again for the help. I will also try to install with pip and see.

I started completely over with a fresh installation of Anaconda.
And set it up with these commands:

conda config --set restore_free_channel true
conda config --env --set subdir osx-64
conda config --set channel_priority disabled

eg. with python3.10, downgraded cutadapt==4.5 to 4.2

ran the command:
miRge3.0 -s SRR772403.fastq.gz -lib miRge3_Lib -a illumina -on human -db mirbase -o output_dir -gff -cpu 8
Here is the full error:

PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
bowtie version: 1.3.1
cutadapt version: 4.2
Samtools error!: samtools, command not found. Type "samtools --version" and check the version
 Use argument -psam <name of the directory>
NOTE: Will not exit unless you encounter this error otherwise
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/mirge/libs/digest.py", line 319, in cutadapt
    if int(cu_ver) >= 3:
NameError: name 'cu_ver' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/au711014/anaconda3/envs/mirge310/bin/miRge3.0", line 10, in <module>
    sys.exit(main())
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/mirge/__main__.py", line 140, in main
    pdDataFrame,sampleReadCounts,trimmedReadCounts,trimmedReadCountsUnique = baking(args, fastq_fullPath, base_names, workDir)
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/mirge/libs/digest.py", line 142, in baking
    a , b = fqres_pairs.result()
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
NameError: name 'cu_ver' is not defined

**Comment by arunhpatil** [comment]
Hi Rolf, 

I have a few things (two methods) I would like you to try and let me know what comes out (using py 3.10 and cutadapt 4.2):
1. can you try the same miRge command with this new parameter `-cuv 4.2` 
2. Can you create a python script with following lines and run it on your command line. lets name it cutadapt_version.py

```
import subprocess
cutadaptCommand = "cutadapt --version"
cutadapt = subprocess.run(str(cutadaptCommand), shell=True, capture_output=True, text=True)
print(cutadapt)
cvnum  = cutadapt.stdout.strip()
print()
print(cvnum)
cutadaptVersion = tuple([ int(num) for num in cvnum.split('.')])
print()
print(cutadaptVersion)
```

Thank you,
Arun.

**Comment by arunhpatil** [comment]
Hi Rolf, 

Please ignore my previous message. I found that the global declarations in Mac (as I see it) is not global for function inside a function (recursive functions). I don't know what is wrong here, but I have a fix for it. A little bit of work on my end to make it a new release, but I hope it won't create a problem in Linux OS.  
[digest.txt](https://github.com/mhalushka/miRge3.0/files/12898691/digest.txt)

This is quick fix, please download this digest.txt file (`right click and save link as / save file as`) and change the extension to digest.py. Move this file `digest.py` to `/Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/mirge/libs/ `folder.

```
mv digest.txt /Users/au711014/anaconda3/envs/mirge310/lib/python3.10/site-packages/mirge/libs/digest.py
```

Please note: my response is generally for all users, and I try to keep my explanation as simple as possible. Please don't mind if my responses are longer to read. 

I hope to have a new release soon (and intend to include a fix for that warning message as well). 

Thank you,
Arun

**Comment by rolfsoekilde** [comment]
Thanks Arun,

Very nice. It works now.

I can do without the samtools for now, but the samtools solution with tbb=2020.2 and openssl=1.0 installation does not work with python3.10.

best,
Rolf

**Comment by arunhpatil** [comment]
Hi Rolf,

Great. Well, I have not used Samtools on the Mac (where I installed the miRge3.0, recently), however I could install via source code only (not conda/Pip unfortunately). The tool seems to work showing the help message. 

Thank you,
Arun.
