### ISSUE TITLE
Question about Read Length Distribution

### ISSUE THREAD

**Issue by hy101** [mhalushka/miRge3.0#87]
I run miRge3.0 like this，with Qiage UMI:
`miRge3.0 -s SRR13077007.fastq -db miRBase -lib miRge3_Lib -on human -a AACTGTAGGCACCATCAAT --qiagenumi -umi 0,12 -o output_dir -cpu 10 -udd`

Is the read length == len(pureSeq) + 12

**Comment by arunhpatil** [comment]
Hi @hy101,

The read length distribution is based on the length of the templates/miRNAs and in your example it would be len(pureSeq). The distribution should have a higher depth around 20-25 nucleotides. If it is left skewed, then probably the adapters were not trimmed well. I hope this answers your question. 

Thank you,
Arun.

**Comment by hy101** [comment]
https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L180-L188

c is for UMICounts not len(pureSeq)

https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L274-L286
UMICounts is then used to plot Read Length Distribution

**Comment by hy101** [comment]
final_seq = pureSeq + umi_seq
https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L339-L344
https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L357-L358
len(final_seq) is used to plot Read Length Distribution
https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L141-L149
https://github.com/mhalushka/miRge3.0/blob/13c9edae738edeb28e98d0e3d6fb40e16c620be9/mirge/libs/digest.py#L265-L273

**Comment by arunhpatil** [comment]
@hy101,

You are right. It does take the length of both template and umi for plotting read length distribution. Thank you for bringing it to our attention. I will make a change for this in the next release. If you wish to make PR, please go ahead.  

Thank you,
Arun.
