### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YoonheeJ** [mhalushka/miRge3.0#9]
Hi,

I am trying to miRge3.0 with mouse samples with below command. but I've got error at the end.
miRge3.0 -s CtlSp-R1.fastq.gz -on mouse -o output_dir -gff -nmir  -ai -cpu 12 -a illumina -db miRBase -lib miRge3_Lib/  -pbwt ~/bowtie-1.3.0-linux-x86_64/ -pr ~/ViennaRNA-2.4.17/src/bin/
bowtie version: 1.3.0
cutadapt version: 3.2
Samtools version: 1.9
RNAfold version: 2.4.17
Collecting and validating input files...

miRge3.0 will process 1 out of 1 input file(s).

Cutadapt finished for file CtlSp-R1 in 109.4189 second(s)
Collapsing finished for file CtlSp-R1 in 1.9577 second(s)

Matrix creation finished in 2.4879 second(s)

Data pre-processing completed in 114.92 second(s)

Alignment in progress ...
Alignment completed in 58.2329 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):

TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

Could you please let me know how to solve this?
Thank you,

**Comment by arunhpatil** [comment]
Hi, 

Sure, the error doesn't specify details about what function and precisely at which point this was picked up. Is it possible for you to send a sample file via email? I will replicate the analysis to resolve the error. 

Also, for a quick resolve, could you tell if conda or pip was used for miRge3.0 installation? 
Is it possible to find out the version of pandas installed? (either pip list or conda list can answer that)

Thank you,
Arun

**Comment by YoonheeJ** [comment]
Hi Arun,

Thanks for the quick response. The file is too big to send via email.
I installed miRge3 with pip.

I tried it again, and showed this error like below.

Alignment in progress ...
Alignment completed in 57.7069 second(s)

Summarizing and tabulating results...
Traceback (most recent call last):
  File "/Zulu/yoonhee/.local/bin/miRge3.0", line 8, in <module>
    sys.exit(main())
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/mirge/__main__.py", line
103, in main
    summarize(args, workDir, ref_db, base_names, pdMapped,
sampleReadCounts, trimmedReadCounts, trimmedReadCountsUnique)
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/mirge/libs/summary.py",
line 749, in summarize
    subpdMapped['miRNA_cbind'] = subpdMapped[['exact miRNA', 'isomiR
miRNA']].apply(lambda x: ''.join(x), axis = 1)
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/frame.py",
line 6878, in apply
    return op.get_result()
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/apply.py",
line 180, in get_result
    return self.apply_empty_result()
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/apply.py",
line 220, in apply_empty_result
    return self.obj._constructor_sliced(r, index=self.agg_axis)
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/series.py",
line 305, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/construction.py",
line 465, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File
"/Zulu/yoonhee/.local/lib/python3.8/site-packages/pandas/core/dtypes/cast.py",
line 1452, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic'
objects>' as a data type

Thank you.
Yoonhee

**Comment by arunhpatil** [comment]
Hi @YoonheeJ 

I suspect there is a conflict with pandas and numpy in your computer, to rule out this possibility I want you to upgrade pandas and try the command again. You can upgrade it as shown below (python3.7 if you are using py37):
```
python3.8 -m pip install --user --upgrade pandas
python3.8 -m pip install --user --upgrade numpy
```
or 
```
pip3 install pandas --upgrade
pip3 install numpy --upgrade
```
Please let me know if this resolves the issue. 

Thank you,
Arun.

**Comment by YoonheeJ** [comment]
Hi Arun,

It worked. Thank you!!

Yoonhee
