### ISSUE TITLE
Does miRge3.0 restrict reverse-complement mapping?

### ISSUE THREAD

**Issue by MilosCRF** [mhalushka/miRge3.0#91]
Hi, 
Is --norc option utilized for bowtie within miRge3.0? 
If yes, could you please specify for which reference RNA libraries the --norc option is typically applied? 

Thanks a lot
Milos

**Comment by MilosCRF** [comment]
This is the answer to my question from the supplementary file of miRge3 paper: 
"Bowtie is run across all libraries with ‘--norc’ option to restrict reads from alignment against the reverse-complement reference strand. "

I apologise for spamming.

**Comment by MilosCRF** [comment]
This is the answer to my question from the supplementary file of miRge3 paper:
"Bowtie is run across all libraries with ‘--norc’ option to restrict reads from alignment against the reverse-complement reference strand. "

I apologise for spamming.

**Comment by arunhpatil** [comment]
@MilosCRF, 

No worries. 

Thank you,
Arun
