### ISSUE TITLE
Issues with counts and adapters

### ISSUE THREAD

**Issue by VilainLab** [mhalushka/miRge3.0#93]
Hello,

Thanks with the great pipeline. I have used this previously for 10-20 samples, and it had worked great, but am currently facing issues, when I am trying to use a sample size of 85 samples. I am running it on our HPC and selected a memory allocation of 400G. Initially I faced issues with running all the samples together, because of out of memory errors. But I figured out that with running one sample at a time in batch (code attached; mirAnalysis.txt). The miRNA sequencing core provided us with the information regarding the adapters.
•    AACTGTAGGCACCATCAAT (19 base Qiagen adapter)
•    NNNNNNNNNNNN (12 base random sequence for UMI)
•    AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC (Illumina adapter sequence)
•    GAGCCAAGTT (example of i7 index sequence)
I use the adapter information for trimminh as you would see in the script attached.

Here I face 2 issues:
1. No read counts registered for the miRNAs: None of the miRNAs report any read counts in the counts.csv files in the result. A subset of the fastq file with 2000 reads (pass.txt), out (miRNAAnalysis_287513_0.out.txt) and the error files (miRNAAnalysis_287513_0.err.txt) are attached.
2. Error Cannot set a DataFrame with multiple columns to the single column miRNA_cbind: For the same run, some of the fastq files fail wit this error.  Fastq file with 2000 reads (fail.txt), error(miRNAAnalysis_287513_1.err.txt) and out(miRNAAnalysis_287513_1.out.txt)

Please let me know if you need any additional information, and thanks again for this nice tool.

Surajit

[mirAnalysis.txt](https://github.com/mhalushka/miRge3.0/files/14779191/mirAnalysis.txt)
[pass.txt](https://github.com/mhalushka/miRge3.0/files/14779184/pass.txt)
[fail.txt](https://github.com/mhalushka/miRge3.0/files/14779185/fail.txt)
[miRNAAnalysis_287513_1.out.txt](https://github.com/mhalushka/miRge3.0/files/14779318/miRNAAnalysis_287513_1.out.txt)
[miRNAAnalysis_287513_1.err.txt](https://github.com/mhalushka/miRge3.0/files/14779319/miRNAAnalysis_287513_1.err.txt)
[miRNAAnalysis_287513_0.out.txt](https://github.com/mhalushka/miRge3.0/files/14779320/miRNAAnalysis_287513_0.out.txt)
[miRNAAnalysis_287513_0.err.txt](https://github.com/mhalushka/miRge3.0/files/14779321/miRNAAnalysis_287513_0.err.txt)

**Comment by arunhpatil** [comment]
Hi @VilainLab,

Thank you, I find a small error in the command used, as the 3' adapter specified should have been `AACTGTAGGCACCATCAAT`, we have a documentation for the Qiagen based UMI below, please let us know if you find miRNA hits after trying this example. 

https://mirge3.readthedocs.io/en/master/quick_start.html#qiagen-based-umi

Also, all other errors should be resolved with the currect specification of adapter at 3' end. Do let us know if the errors still persists. (Correction: This is Qiagen adapter AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC, Illumina is TGGAATTCTCGGGTGCCAAGGAACTCCAG.... details [here](https://github.com/mhalushka/miRge3.0/issues/20))

Thank you,
Arun.
