### ISSUE TITLE
Samples with different adapters

### ISSUE THREAD

**Issue by adamcatto** [mhalushka/miRge3.0#94]
I have a collection of 10 samples, each of which used a different adapter sequence. However it seems that while the samples flag takes arbitrary number of arguments, there is only one adapter sequence allowed, rather than potentially one for each. Is there a way around this or do I need to re-run the pipeline for each sample separately?

**Comment by adamcatto** [comment]
Also, I wonder if there is an option to detect the 5' / 3' adapter sequences for each sample via e.g. cutadapt.

**Comment by mhalushka** [comment]
miRge does not have the capability of letting you removed many different types of adapters. The two choices you have are to run each of the files through Cutadapt individually and use the output files of those runs in a combined miRge run. Or you can run them through miRge one at a time, each with the appropriate adaptive parameters. 
For your second question, if I am using public data and do not know the adapter a priori, I will do a grep search on a common miRNA (ex miR-21) and see what the sequences are ahead and behind the canonical sequence.

**Comment by arunhpatil** [comment]
Hi @adamcatto,

I agree with Marc and as Marc suggested, we don't auto detect the adapter sequences. 

I guess you have all samples sequenced in the same platform, and may include additional random barcodes of 4 nucleotiedes on both ends for each sample. If this is the case, then you cut 4 N on both ends -u 4 -u -4. Let me know if this helps. Also, you could send us subest/sample data for us to try and guide you.

Thank you,
Arun.
