### ISSUE TITLE
Unmapped reads

### ISSUE THREAD

**Issue by hamzaaitabbou96** [mhalushka/miRge3.0#95]
Hi,  

Can I extract the FASTA file of unmapped Sequences for later processing.

**Comment by arunhpatil** [comment]
Hi @hamzaaitabbou96,

You can write all the collapsed sequences post QC and adapter processing using the `tcf` parameter [-tcf   --tcf-out            switch to write trimmed and collapsed fasta file (Default: off)], however we currently don't have an option for getting just the unmapped sequences. Also, all the unmapped sequences are stored as a csv file and you can convert that to a fasta file by assigning appropriate header to each read. It should be straight forward this way. Let me know if this is of help. (I am travelling and will be at my desk on May 04). 

Thank you,
Arun.
